#ifndef PINDEFINITIONS_H
#define PINDEFINITIONS_H

#define PIN_ACCELEROMETER_INTERUPT 19

#define PIN_STEERING_MOTOR 33

#define PWM_CHANNEL0 0
#define PWM_CHANNEL1 1
#define PWM_CHANNEL2 2
#define PWM_CHANNEL3 3
#define PWM_FREQ 5000
#define PWM_RESO 8

#define PIN_IMPULSION_FORWARD 5
#define PIN_IMPULSION_BACKWARD 32
#define PIN_IMPULSION_ENABLE 18
#define PWM_CHANNEL_FORWARD 4
#define PWM_CHANNEL_BACKWARD 5

#define PIN_ULTRASOUND_TRIG 23
#define PIN_ULTRASOUND_ECHO 35

#endif