#ifndef PINDEFINITIONS_H
#define PINDEFINITIONS_H

#define PIN_ACCELEROMETER_INTERUPT 19

#define PIN_STEERING_MOTOR 33

#define PWM_CHANNEL0 0
#define PWM_CHANNEL1 1
#define PWM_CHANNEL2 2
#define PWM_CHANNEL3 3

#define PIN_IMPULSION_FORWARD 5
#define PIN_IMPULSION_BACKWARD 32
#define PIN_IMPULSION_ENABLE 18

#endif