M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date Thu 11 Jan 2024 12:10:53 PM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-11T12:10:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X3.8925Y-2.2
X3.8925Y-3.2
X3.8925Y-4.2
T0
M30
